server:
  port: 8080

spring:
  application:
    name: personal-loan-los
  datasource:
    url: jdbc:postgresql://localhost:5432/personal_loan
    username: postgres
    password: Shri@1927
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: personal-loan-los
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

app:
  security:
    issuer: personal-loan-los
    access-token-minutes: 15
    refresh-token-days: 7
  kafka:
    topics:
      workflow-events: loan-workflow-events
